spring:
  datasource:
      type: org.apache.commons.dbcp2.BasicDataSource # 注意这里要指定数据库连接池的类型
      url: jdbc:mysql://127.0.0.1:3306/flood?useUnicode=true&CharacterEncoding=UTF-8
      username: root
    #  password: root
      password: HFRi7bzMJVme
      driver-class-name: com.mysql.cj.jdbc.Driver
      dbcp2:  # 表示的是连接池的配置  database connnection pool 2 的缩写
        min-idle: 5
        initial-size: 5
        max-idle: 5
        max-wait-millis: 2000
  application:
    name: demo-service
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

security:
  require-ssl: true
server:
  ssl:
    key-store: /etc/letsencrypt/live/seeld.eu/keystore.p12
    key-store-password: guang4196
    key-store-type: PKCS12
    key-alias: tomcat
  port: 80
  tomcat:
    max-threads: 128
    max-connections: 1024
    remote-ip-header: x-forwarded-for
    uri-encoding: UTF-8
    accesslog:
      directory: /var/log/flood/
      enabled: true
      pattern: common
      prefix: flood-access
      rotate: true
      suffix: .log

mybatis:
  mapperLocations: classpath*:mapper/*.xml

export:
  filePath: /var/file/flood/temp/

logging:
  config: classpath:logback-spring-default.xml
  path: /var/log/flood
  level: DEBUG
