spring:
  datasource:
      type: org.apache.commons.dbcp2.BasicDataSource # 注意这里要指定数据库连接池的类型
      url: jdbc:mysql://127.0.0.1:3306/flood?useUnicode=true&CharacterEncoding=UTF-8
      username: root
      password: HFRi7bzMJVme
      driver-class-name: com.mysql.cj.jdbc.Driver
      dbcp2:  # 表示的是连接池的配置  database connnection pool 2 的缩写
        min-idle: 5
        initial-size: 5
        max-idle: 5
        max-wait-millis: 2000
  application:
    name: demo-service
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

server:
  port: 8081

mybatis:
  mapperLocations: classpath*:mapper/*.xml

export:
  filePath: /home/flood/file/temp/


